var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "       o                                                                        ",
   "     @          oo     d              m    oo                                   ",
   "  xxxxx        xxxxxxxxxx              xxxxxxxxx                           o    ",
   "                  x   o      xxx          x    x                           xxxxx",
   "            x     x   m               m        x            o          x        ",
   "                  x   o                                     o                   ",
   "               xxxxxxxxxx            xxxx                         xx       xx   ",
   "                           xx   o                   xx      xx          oo      ",
   "              o                o o  x      xx          !!v!!   !!!! o  o x!!!   ",
   "       xxxx      xxxx     !!  o o o    =                               xx!xx    ",
   "              x              o  o  o                    x x                     ",
   "            !!!!!           o o o o o                               xx          ",
   "xxxx                 xx    o o  o  o o    xx   o o  x                           ",
   "                          o  o  o  o  o                       m                 ",
   "                  xxx    o    o o o    o    xxx             xxxx                ",
   "     x                  o o o o o o o o o               o          d            ",
   "      m                                                x        xxxxx           ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx x xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                o  o  xx         o  o                             ",
   "                                                            x o      o    o    o      o                           ",
   "                                                             o        o o   o o        o                          ",
   "                                                             o        o       o        o                    xxxxxx",
   "                                                      xx      o      o    xx   o      o                           ",
   "                                     o                          o  o             o  o      xxxxx                  ",
   "                                    o                                 m                              xx           ",
   "                                   o            xx             xxxxxxxxxxxxxxxxxxxxxxxxx                          ",
   "                                  o o o                                                                           ",
   "                                     o                                                        xx                  ",
   "                                    o o o   xxxxxxx                  xxx                                          ",
   "                                 xx    o                                                                   o      ",
   "                                      o               xxx       =          xxx                            ooo     ",
   "                                     o                                                                   ooooo    ",
   "                                    xxxx                    xxxxxxx                                      ooooo    ",
   "                                          xxx                               x              xxxxx  d       oxo     ",
   "                             xxxx                                         xxxxx                 xxxx       x      ",
   "   @                d   o           x                                   xxxxxxxxx                      x   x   x  ",
   "xxxxxx     o       xxx             xxx                                xxxxxxxxxxxxx                      x x x    ",
   "               x                 xxxxxxx                xx          xxxxxxxxxxxxxxxxx                      x      ",
   "                    =          xxxxxxxxxxx   x     xx         oo  xxxxxxxxxxxxxxxxxxxxx  xxx    = = x  x   x      ",
   "         x                   xxxxxxxxxxxxxxx                    xxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!x  x      ",
   "       xxxxx               xxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!x x      ",
   "     xxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!! x      ",
   "   xxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!! x  x!!!",
   " xxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!! x x!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!! x !!!!!"],
  ["                                                                                                             ",                                                                                                             
   "                                                            o  o  o                                          ",
   "                                                          o         o                                        ",
   "                                                         o     x       o                                     ",
   "                                                        o           x    o                                   ",
   "                                                           x                                                 ",
   "                                                    d                x      x                                ",
   "          x      x                                     x             x      x                                ",
   "       x  x      x                                  x                x  o   x                                ",
   "          x   o  x                                  xx                x    x                                 ",
   "           x    x                                   xxxxxx              xx                                   ",
   "   xxxx      xx                         =           xx        x         xx                                   ",
   "             xx       xxx                           x                   xx                                   ",
   "             xx                   x                                     xx                                   ",
   "         xx  xx               x      x      x   x               xxx     xx                                   ",
   "    o        xx                      x      x      =                    xx                ooo                ",
   "             xx                      x   o  x          xx   o           xx          x                        ",
   "    xx       xx                       x    x              xxxx          xx          xx          m            ",
   "             xx                         xx                              xx          xxxxxxx    xxxxxx        ",
   "             xx                         xx                 m            xx          xx                  o    ",
   "        xx   xx                         xx        o  xxxxxxxxxxxxxxx    xx          x                  x     ",
   "             xx                         xx        x                     xx                                 o ",
   "    xx       xx                         xx                              xx                                 x ",
   "       o     xx                         xx                              xx                                   ",
   "       x     xx                         xx                              xx                                   ",
   " xx          xx                         xx                              xx                                   ",
   "             xx                         xx                              xx                             xxxxxx",
   "  @          xx                         xx                              xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx",
   "xxxxxx       xx                         xx                              xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx",
   "       o     xx                         xx                              xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx",
   " =           xx                         xx                              xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx",
   "             xx!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx",
   "xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx"],
  ["                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
   "          x               x  x      @                     x                                                  ",
   "           x             x                                x                                                  ",
   "            x     x     x    x  xxxxx  xxxxx  xxxx  xxxx  x                                                  ",
   "             x   x x   x     x  x   x  x   x  x xx  x  x  x                                                  ", 
   "              x x   x x      x  x   x  x   x  x     x                                                        ",
   "               x     x       x  x   x  x   x  xxxx  x     x                                                  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],



];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
